### PR TITLE
PHP Coding Standards Fixer v3 Support

### LINKED ISSUE #20: php-cs-fixer ^3.0 compatibility issue
Stop working after upgrade to version 3.0 of php-cs-fixer.

I've changed the config file to the new ".php_cs.dist.php" but, It keeps throwing "Unknown Error".

I tried to debug but my knowledge of VSCode extensions and NodeJS is limited
Only thing I know is that execution returns Error Code "255", but couldn't be able to know why.

When I've downgraded to ^2.19 version of php-cs-fixer everything back to work again.

Appreciate any help.

### PR DESCRIPTION
**Pull request by PHLAK**
**Disclaimer:** I am not familiar with VS Code extension development and have no idea if there's any other changes that need to be made here and would greatfully accept any feedback on how this PR could be improved in that regard (or in general).

---

PHP Coding Standards Fixer [3.0.0](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v3.0.0) was tagged back in May and this came with some breaking changes which can be seen in the [upgrade guide](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.0/UPGRADE-v3.md). In particular the configuration file naming conventions were updated according to the following table.

| 2.x              | 3.0                      |
| ---------------- | ------------------------ |
| `.php_cs`        | `.php-cs-fixer.php`      |
| `.php_cs.dist`   | `.php-cs-fixer.dist.php` |
| `.php_cs.cache`  | `.php-cs-fixer.cache`    |

These changes cause errors in VS Code when using the default values of this extension and v3.X of the `friendsofphp/php-cs-fixer` package.

<p align="center">
    VS Code Error
</p>

This PR updates the use of `.php_cs.dist` to `.php-cs-fixer.dist.php` to enable support for php-cs-fixer v3 which I believe should be the default going forward.

Resolves #20

### CODE REVIEW

**Comment by PHLAK** [comment]
For anyone landing here in the mean time you can override the default configuration file in the extension settings to set this globally or to override this per-project you can create a file at `.vscode/settings.json` with the following contents.

```json
{
    "simple-php-cs-fixer.config": ".php-cs-fixer.dist.php"
}
```

**Comment by PHLAK** [comment]
Hey @calebporzio, sorry to bother you but can we get a review/comment on this when you have a chance?

**Comment by calebporzio** [comment]
Hi @PHLAK, thanks for the PR - I think with this change if we deployed to the marketplace, it would break people's set ups who are using the 2.x convention.

I'm not really sure what to do in these cases besides allowing both in the code. Is that possible?

**Comment by PHLAK** [comment]
> allowing both in the code. Is that possible?

Allowing both 3.X and 2.X configurations would be best. Maybe we can change the `config` field to an array that is looped over checking for file existence using the first it finds. 

```javascript
{
    "simple-php-cs-fixer.config": ['.php-cs-fixer.php', '.php-cs-fixer.dist.php', '.php_cs', '.php_cs.dist']
}
```

This would also allow the extension to check for the existence of '.php-cs-fixer.php' before '.php-cs-fixer.dist.php' which is the [expected behavior](https://cs.symfony.com/doc/config.html#config-file).

> ... you can save the project configuration in a `.php-cs-fixer.dist.php` file in the root directory of your project. ... You may also create `.php-cs-fixer.php` file, which is the local configuration that will be used instead of the project configuration.

---

> ... if we deployed to the marketplace, it would break people's set ups who are using the 2.x convention.

True but with the current configuration set ups that are using the 3.x convention (the default going forward) are broken.

**Comment by PHLAK** [comment]
Another possible solution would be **not** passing the `--config` option by default and let php-cs-fixer handle locating the configuration file itself. In this case we could keep the the `simple-php-cs-fixer.config` option in the extension but default it to `null` or an empty value. If set it would add the `--config` option to override the default.

**Comment by calebporzio** [comment]
Yeah, that's probably a better idea. If you PR and test it I'll merge it. Or better yet, wanna be a co maintainer on this repo? I don't use this myself anymore and don't want to be the sole maintainer...

**Comment by PHLAK** [comment]
Thanks, I'll work on making the changes to not pass the `--config` option by default.

> wanna be a co maintainer on this repo

I'm not familiar with VS Code extension development at all but am willing to learn. If that's not a major concern then I'm in.

**Comment by PHLAK** [comment]
After digging a little deeper I see there's already a `simple-php-cs-fixer.useConfig` option defined. When set to `false` the `--config` command line option is not passed.

https://github.com/calebporzio/simple-php-cs-fixer/blob/dec3addbf2042f25cdfd815f15a01f721882c458/extension.js#L77

https://github.com/calebporzio/simple-php-cs-fixer/blob/dec3addbf2042f25cdfd815f15a01f721882c458/extension.js#L25-L36

However, this option currently defaults to `true` meaning the `--config` option _is_ passed along with the value of `simple-php-cs-fixer.config` (current default of `.php_cs.dist`).

https://github.com/calebporzio/simple-php-cs-fixer/blob/dec3addbf2042f25cdfd815f15a01f721882c458/package.json#L38-L47

I have updated this to `false` which I believe will be reflected when the extension is updated unless the user has explicitly added it to their `settings.json` file.

**Comment by PHLAK** [comment]
@calebporzio I believe this PR is good to go but let me know if there's anything else needed.

**Comment by PHLAK** [comment]
Hey @calebporzio is there anything else needed to get this merged?

Sorry if I'm being a bother, I understand you're busy with other things. I'm willing to co-maintain this repo as you offered to take some of that responsibility off your hands. Just let me know what's up.

**Comment by PHLAK** [comment]
I was getting errors from this extension so I forked it, merged this PR (and #23) and published it to the marketplace as [PHP CS Fixer 3](https://marketplace.visualstudio.com/items?itemName=PHLAK.simple-php-cs-fixer-3&ssr=false#overview) so I can have a working extension again. If you ever wish to merge these changes in the future let me know and I'll open a new PR.

**Pull request closed without merging**
